
INSERT INTO achievements (name, description, icon, category, requirement_type, requirement_value, points) VALUES
('Primeiro Treino', 'Complete seu primeiro treino', '💪', 'workout', 'workouts_completed', 1, 10),
('Dedicação Semanal', 'Complete 7 treinos', '📅', 'workout', 'workouts_completed', 7, 20),
('Guerreiro do Mês', 'Complete 30 treinos', '🏆', 'workout', 'workouts_completed', 30, 50),
('Centurião', 'Complete 100 treinos', '👑', 'workout', 'workouts_completed', 100, 100),
('Primeira Refeição', 'Registre sua primeira refeição', '🍎', 'nutrition', 'meals_logged', 1, 10),
('Nutrição em Dia', 'Registre 30 refeições', '☕', 'nutrition', 'meals_logged', 30, 30),
('Mestre da Nutrição', 'Registre 100 refeições', '🍽️', 'nutrition', 'meals_logged', 100, 80),
('Primeira Foto', 'Tire sua primeira foto de progresso', '📸', 'progress', 'photos_taken', 1, 15),
('Jornada Visual', 'Tire 10 fotos de progresso', '🖼️', 'progress', 'photos_taken', 10, 40),
('Primeiro Recorde', 'Estabeleça seu primeiro recorde pessoal', '🎯', 'records', 'personal_records', 1, 15),
('Colecionador de PRs', 'Estabeleça 10 recordes pessoais', '🏅', 'records', 'personal_records', 10, 50),
('Atleta Completo', 'Treine 3 modalidades diferentes', '⚡', 'variety', 'sports_practiced', 3, 25),
('Versátil', 'Treine 6 modalidades diferentes', '✨', 'variety', 'sports_practiced', 6, 40),
('Multi-esporte', 'Treine todas as 12 modalidades', '🌟', 'variety', 'sports_practiced', 12, 100),
('Sequência Iniciada', 'Mantenha 3 dias seguidos treinando', '🔥', 'streak', 'current_streak', 3, 15),
('Consistência', 'Mantenha 7 dias seguidos treinando', '🚀', 'streak', 'current_streak', 7, 30),
('Inabalável', 'Mantenha 30 dias seguidos treinando', '⚡', 'streak', 'current_streak', 30, 100),
('Explorador', 'Experimente 20 exercícios diferentes', '🔍', 'exploration', 'exercises_tried', 20, 25),
('Conhecedor', 'Experimente 50 exercícios diferentes', '📚', 'exploration', 'exercises_tried', 50, 50),
('Mestre dos Exercícios', 'Experimente 100 exercícios diferentes', '📖', 'exploration', 'exercises_tried', 100, 100),
('Força Bruta', 'Levante mais de 100kg em um exercício', '💪', 'strength', 'max_weight_kg', 100, 60),
('Titã', 'Levante mais de 200kg em um exercício', '🏆', 'strength', 'max_weight_kg', 200, 120),
('Iniciante Dedicado', 'Complete 20 treinos no nível iniciante', '⭐', 'progression', 'beginner_workouts', 20, 25),
('Intermediário', 'Complete 20 treinos no nível intermediário', '🏅', 'progression', 'intermediate_workouts', 20, 40),
('Avançado', 'Complete 20 treinos no nível avançado', '👑', 'progression', 'advanced_workouts', 20, 60),
('Madrugador', 'Complete 10 treinos antes das 8h', '🌅', 'timing', 'morning_workouts', 10, 30),
('Guerreiro Noturno', 'Complete 10 treinos após às 20h', '🌙', 'timing', 'night_workouts', 10, 30),
('Perfeccionista', 'Mantenha 95% de precisão de forma em 20 exercícios', '👁️', 'quality', 'form_accuracy', 95, 80),
('Hidratação Diária', 'Registre água por 7 dias seguidos', '💧', 'wellness', 'water_streak', 7, 20),
('Bem-Estar Completo', 'Use todas as ferramentas do app', '❤️', 'engagement', 'features_used', 10, 50);
