
INSERT INTO achievements (name, description, icon, category, requirement_type, requirement_value, points) VALUES
('Primeiro Passo', 'Crie seu primeiro perfil', '👤', 'engagement', 'profile_created', 1, 5),
('Semana Completa', 'Complete pelo menos um treino em cada dia da semana', '📅', 'streak', 'week_complete', 1, 50),
('Mês de Ouro', 'Treine durante 30 dias consecutivos', '🏆', 'streak', 'current_streak', 30, 150),
('Maratonista Mental', 'Treine durante 60 dias consecutivos', '🔥', 'streak', 'current_streak', 60, 250),
('Lenda Viva', 'Treine durante 100 dias consecutivos', '👑', 'streak', 'current_streak', 100, 500),
('Nutricionista Amador', 'Registre 50 refeições', '🥗', 'nutrition', 'meals_logged', 50, 40),
('Chef Saudável', 'Registre 200 refeições', '👨‍🍳', 'nutrition', 'meals_logged', 200, 120),
('Mestre da Alimentação', 'Registre 500 refeições', '🍽️', 'nutrition', 'meals_logged', 500, 200),
('Transformação Visual', 'Tire 5 fotos de progresso', '📷', 'progress', 'photos_taken', 5, 25),
('Documentário Vivo', 'Tire 20 fotos de progresso', '🎬', 'progress', 'photos_taken', 20, 80),
('Coleção PRs', 'Estabeleça 5 recordes pessoais', '🎯', 'records', 'personal_records', 5, 30),
('Quebrando Limites', 'Estabeleça 20 recordes pessoais', '💪', 'records', 'personal_records', 20, 100),
('Lendário', 'Estabeleça 50 recordes pessoais', '⚡', 'records', 'personal_records', 50, 250),
('Explorador Fitness', 'Treine 5 modalidades diferentes', '🎯', 'variety', 'sports_practiced', 5, 30),
('Atleta Polivalente', 'Treine 8 modalidades diferentes', '🌟', 'variety', 'sports_practiced', 8, 60),
('Experimentador', 'Experimente 30 exercícios diferentes', '🧪', 'exploration', 'exercises_tried', 30, 30),
('Biblioteca Viva', 'Experimente 150 exercícios diferentes', '📚', 'exploration', 'exercises_tried', 150, 150),
('Superman', 'Levante mais de 150kg em um exercício', '🦸', 'strength', 'max_weight_kg', 150, 80),
('Hercules', 'Levante mais de 250kg em um exercício', '⚡', 'strength', 'max_weight_kg', 250, 200),
('Progressão Iniciante', 'Complete 10 treinos no nível iniciante', '🌱', 'progression', 'beginner_workouts', 10, 15),
('Evoluindo', 'Complete 10 treinos no nível intermediário', '📈', 'progression', 'intermediate_workouts', 10, 25),
('Expert', 'Complete 10 treinos no nível avançado', '🏆', 'progression', 'advanced_workouts', 10, 40),
('Raio de Sol', 'Complete 5 treinos antes das 7h', '☀️', 'timing', 'morning_workouts', 5, 20),
('Coruja da Noite', 'Complete 5 treinos após às 21h', '🦉', 'timing', 'night_workouts', 5, 20),
('Olho de Águia', 'Mantenha 90% de precisão de forma em 10 exercícios', '🦅', 'quality', 'form_accuracy', 90, 50),
('Hidratação Pro', 'Registre água por 14 dias seguidos', '💦', 'wellness', 'water_streak', 14, 40),
('Guru do H2O', 'Registre água por 30 dias seguidos', '🌊', 'wellness', 'water_streak', 30, 80),
('Explorador Completo', 'Use todas as funcionalidades do app pelo menos uma vez', '🎯', 'engagement', 'features_used', 15, 100),
('Guerreiro do Treino', 'Complete 50 treinos', '⚔️', 'workout', 'workouts_completed', 50, 70),
('Veterano', 'Complete 200 treinos', '🛡️', 'workout', 'workouts_completed', 200, 200),
('Mestre do Tempo', 'Complete 500 treinos', '⏱️', 'workout', 'workouts_completed', 500, 500),
('Dieta Balanceada', 'Mantenha macros balanceados por 7 dias', '⚖️', 'nutrition', 'balanced_days', 7, 60),
('Nutrição Perfeita', 'Mantenha macros balanceados por 30 dias', '✨', 'nutrition', 'balanced_days', 30, 150),
('Volume Master', 'Acumule 100.000kg de volume total levantado', '💪', 'strength', 'total_volume_kg', 100000, 150),
('Titã do Volume', 'Acumule 500.000kg de volume total levantado', '🏔️', 'strength', 'total_volume_kg', 500000, 300),
('Primeira Semana', 'Complete 3 treinos em uma semana', '📆', 'workout', 'workouts_completed', 3, 15),
('Social Fitness', 'Compartilhe 5 conquistas', '📱', 'social', 'shares', 5, 25),
('Influencer Fit', 'Compartilhe 20 conquistas', '⭐', 'social', 'shares', 20, 80),
('Meta Alcançada', 'Atinja sua meta de peso', '🎯', 'progress', 'weight_goal_reached', 1, 200),
('Transformação 10kg', 'Perca ou ganhe 10kg de forma saudável', '🔄', 'progress', 'weight_change_10kg', 1, 150);
